# Generated by Django 5.0.6 on 2024-08-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingform',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='Arrival',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='How_Many',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='Leaving',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='Where_To',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='created',
        ),
    ]
