# Generated by Django 5.0.6 on 2024-08-04 07:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_bookingform_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingForm',
            new_name='BookingFormform',
        ),
    ]
