# Generated by Django 5.0.6 on 2024-08-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Subscribers',
        ),
    ]
