# Generated by Django 5.0.6 on 2024-08-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_subscriber_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
