# Generated by Django 5.0.6 on 2024-08-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_subscribers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_desc',
            name='day1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day6',
            field=models.TextField(),
        ),
    ]
