# Generated by Django 5.0.6 on 2024-07-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_appointment_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='subitted_date',
            new_name='appointment_date',
        ),
    ]
