# Generated by Django 5.0.6 on 2024-07-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_subitted_date_appointment_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='subitted_date',
        ),
    ]
